# Generated by Django 4.0.5 on 2022-10-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contentt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='Yazı')),
                ('yazar', models.CharField(max_length=50, verbose_name='Yazar')),
                ('new_date', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Zamanı')),
            ],
        ),
    ]
