# Generated by Django 4.0.5 on 2022-10-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appmy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('text', models.TextField(verbose_name='Yorum')),
                ('com_date', models.DateTimeField(auto_now_add=True, verbose_name='Yorum Saati')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Appmy.contentt', verbose_name='Post')),
            ],
        ),
    ]
